import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.6.1"

    const val retrofit2_kotlin_coroutines_adapter: String = "0.9.2"

    const val com_android_tools_build_gradle: String = "3.6.0-alpha12"

    const val com_jakewharton_timber: String = "5.0.0-SNAPSHOT"

    const val com_squareup_retrofit2: String = "2.6.1"

    const val org_jetbrains_kotlinx: String = "1.1.1"

    const val androidx_test_runner: String = "1.1.0-beta01"

    const val org_jetbrains_kotlin: String = "1.3.50"

    const val androidx_navigation: String = "2.1.0"

    const val androidx_lifecycle: String = "2.2.0-alpha04"

    const val constraintlayout: String = "1.1.3"

    const val espresso_core: String = "3.1.0-beta01"

    const val lint_gradle: String = "26.6.0-alpha12"

    const val appcompat: String = "1.1.0"

    const val material: String = "1.0.0"

    const val aapt2: String = "3.6.0-alpha12-5836729"

    const val junit: String = "4.12"

    /**
     * Current version: "5.6.1"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "5.6.2"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
